platform :ios, '12.0'
use_frameworks!

target 'template' do
  pod 'Pulley', '~> 2.7.0'
  pod 'SnapKit', '~> 5.0.1'
  pod 'SwiftDate', '~> 6.0.3'
  pod 'SwiftyBeaver', '~> 1.7.0'
  pod 'RxSwift', '~> 5'
  pod 'SwifterSwift', '~> 5.0.0'
  pod 'DSGradientProgressView', '~> 1'
  pod 'GoogleMaps', '~> 3.3.0'
  pod 'OverlayContainer'
end
